#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

frameworkVersion=net45
netfx=${frameworkVersion#net}

echo "[INFO] Target framework: ${frameworkVersion}"

echo "[INFO] Run 'mcs' to build bin/Nedap.Retail.Api.dll"
mcs -sdk:${netfx} -r:../target/Nedap.Retail.Api.dll,\
System.ComponentModel.DataAnnotations.dll,\
System.Configuration.dll,\
System.Runtime.Serialization.dll \
-target:exe \
-out:../target/NedapRetailApiExample.exe \
-recurse:'NedapRetailApiExample/*.cs' \
-doc:../target/NedapRetailApiExample.xml \
-platform:anycpu

cp -f NedapRetailApiExample/App.config ../target/NedapRetailApiExample.exe.config

if [ $? -ne 0 ]
then
  echo "[ERROR] Compilation failed with exit code $?"
  exit 1
else
  echo "[INFO] bin/NedapRetailApiExample.exe was created successfully"
fi
